unbind r
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# ── Hotkeys ──────────────────────────
unbind C-b
set -g prefix C-a
bind C-a send-prefix
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
# bind -n M-\` last-window
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind e setw synchronize-panes
bind c new-window -c "#{pane_current_path}"

# ── General Settings ─────────────────────
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 10000
set -sg escape-time 0
set -g set-clipboard on
set -g detach-on-destroy off
set -g allow-passthrough on
set -g default-shell /bin/zsh

# ── Terminal Colors ──────────────────────
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:Tc"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# ── Copy Mode ────────────────────────────
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi Escape send-keys -X cancel

# ── Status Bar ────────────────────────────
set -g status-position top
set -g status-left-length 100
set -g status-style "fg=#D8DEE9,bg=default"
set -g status-left "#[fg=#A3BE8C,bold] #S #[fg=#ABB2BF,nobold] | "
# set -g status-right " %H:%M %d-%b "
set -g status-right ""
set -g window-status-current-format "#[fg=#88C0D0,bold]  #[underscore]#I:#W#[nounderscore]#{?window_zoomed_flag, 󰍋 ,}"
set -g window-status-format "#[fg=#ABB2BF] #I:#W"
set -g message-style "fg=#D8DEE9,bg=default"
set -g mode-style "fg=#3B4252,bg=#81A1C1"
set -g pane-border-style "fg=#3B4252"
set -g pane-active-border-style "fg=#A3BE8C"

# ── TPM Plugin Manager ───────────────────
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect' # tmuxp можно попробовать
set -g @plugin 'christoomey/vim-tmux-navigator'

# set -g @plugin 'dracula/tmux'
# set -g @plugin 'arcticicestudio/nord-tmux'
run '~/.tmux/plugins/tpm/tpm'
