include current-theme.conf

# ── Fonts & Cursor ───────────────────────
# font_family Roboto Mono
# font_family JetBrainsMono Nerd Font
font_family FiraCode Nerd Font
# font_family MesloLGS NF
# font_family Hack Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

cursor_shape block
shell_integration no-cursor
cursor_trail 3
cursor_trail_decay 0.1 0.2


# ── Terminal Behavior ────────────────────
scrollback_lines 5000
confirm_os_window_close 0
mouse_hide_wait 2.0
remember_window_size  no
remember_window_position yes
initial_window_width  1100
initial_window_height 950


# ── UI & Tabs ────────────────────────────
hide_window_decorations yes
tab_bar_edge top
tab_bar_background none
tab_bar_style powerline
tab_powerline_style slanted
# tab_title_template "{title.split('/')[-1]}" 
# tab_title_template "{fmt.fg.c2c2c2}{tab.active_wd.rsplit('/', 1)[-1]}"
tab_title_template "{fmt.fg.red}{'󰍋 ' if layout_name == 'stack' else ''}{fmt.fg.tab}{title.split('/')[-1]}"

background_opacity 0.98
dynamic_background_opacity yes

# active_border_color #fcee0b 
# active_border_color #615f5e
# inactive_border_color #cccccc


# ── System & Integrations ────────────────
allow_remote_control yes
listen_on unix:@mykitty
enabled_layouts tall,fat,grid,stack


# ── 鍵盤快速鍵 ───────────────────────────
kitty_mod ctrl+alt

map super+c         copy_to_clipboard
map super+v         paste_from_clipboard
map kitty_mod+s     paste_from_selection

# windows
map kitty_mod+enter launch --cwd=current
map kitty_mod+x     close_window
map kitty_mod+z     toggle_layout stack

map ctrl+h     neighboring_window left
map ctrl+l     neighboring_window right
map ctrl+k     neighboring_window up
map ctrl+j     neighboring_window down

# tabs
map kitty_mod+c     launch --cwd=current --type=tab
map kitty_mod+n     next_tab
map kitty_mod+p     previous_tab
map kitty_mod+;     set_tab_title
map ctrl+f2         detach_window
map ctrl+f3         detach_window new-tab
map alt+grave       goto_tab 0
map alt+1           goto_tab 1
map alt+2           goto_tab 2
map alt+3           goto_tab 3
map alt+4           goto_tab 4
map alt+5           goto_tab 5

# opacity
map kitty_mod+[  set_background_opacity -0.01
map kitty_mod+] set_background_opacity +0.01
map kitty_mod+/  set_background_opacity 1.0

# scroll
map ctrl+f11        scroll_line_up
map ctrl+f12        scroll_line_down
map ctrl+page_up    scroll_page_up
map ctrl+page_down  scroll_page_down

# utils
map f11 launch --allow-remote-control kitty +kitten broadcast
